services:

  client:
    build: ./client
    volumes:
      - ./client:/app            
      - /app/node_modules
    environment:
      - WEB_SERVER_URL=http://localhost:80
      # pentru hot reloading in docker
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  api:
    build: ./server
    environment:
      - WEB_SERVER_URL=http://localhost:80
      - DB_SERVER_URL=mongodb://db:27017/StayOnTrack
    env_file:
      - ./server/.env
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  
   
