services:
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5001

  api:
    build: ./server
    ports: 
      - "5001:5000"
    environment:
      - DB_SERVER_URL=mongodb://db:27017/StayOnTrack
      - WEB_SERVER_URL=http://localhost:80
      - API_SERVER_URL=http://localhost:5001
    env_file:
      - ./server/.env.development

  db:
    image: mongo:latest
    ports:
      - "27016:27017"

  
   
