apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api-strip
  namespace: stayontrack
spec:
  stripPrefix:
    prefixes:
      - "/api"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stayontrack-api-ingress
  namespace: stayontrack
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: stayontrack-api@kubernetescrd
spec:

 # Userul face cerere catre hostul de mai jos
  # prima data se verifica catre ce route a facut
  # ca a facut catre cea de api(backend)
  # atunci o sa-l redirectioneze catre serviciul
  # de backend, totodata mai sus am pus annotations
  # care se ocupa de rescrierea URL-ului si 
  # serverul de backend va prima ruta fara /api
  ingressClassName: traefik
  rules:
  - host: stayontrack.site
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: stayontrack-api
            port:
              number: 5000
